
apply plugin: 'com.android.library'

dependencies {
    implementation fileTree(dir: 'libs', include: ['*.jar'])
    implementation 'com.android.billingclient:billing:8.0.0'
}

android {
    namespace 'air.com.freshplanet.ane.AirInAppPurchase'

    useLibrary  'org.apache.http.legacy'

    compileSdkVersion 35
    buildToolsVersion '35.0.0'

    defaultConfig {
        minSdkVersion 19
        targetSdkVersion 35
    }
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }
}

task copyDependencies(type: Copy) {
    configurations.implementation.setCanBeResolved(true)
    from configurations.implementation
    into 'dependencies'
}